-- Schema cho PHP 8.2 + MySQL 8 / MariaDB 10.4.
-- Chạy trên database riêng; script sẽ drop các bảng cùng tên nếu đã tồn tại.

CREATE DATABASE IF NOT EXISTS room_booking
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE room_booking;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS NhatKyHeThong;
DROP TABLE IF EXISTS ThongBao;
DROP TABLE IF EXISTS PhongBiKhoa;
DROP TABLE IF EXISTS YeuCauGiaiPhongLich;
DROP TABLE IF EXISTS SlotPhong;
DROP TABLE IF EXISTS PhieuDatPhongPhong;
DROP TABLE IF EXISTS PhieuDatPhong;
DROP TABLE IF EXISTS LichChinhThuc;
DROP TABLE IF EXISTS DotImportLich;
DROP TABLE IF EXISTS PhanCongGiangDay;
DROP TABLE IF EXISTS LopHocPhan;
DROP TABLE IF EXISTS HocPhan;
DROP TABLE IF EXISTS NgayNghi;
DROP TABLE IF EXISTS KhungTiet;
DROP TABLE IF EXISTS HocKy;
DROP TABLE IF EXISTS PhongThietBi;
DROP TABLE IF EXISTS ThietBi;
DROP TABLE IF EXISTS Phong;
DROP TABLE IF EXISTS ToaNha;
DROP TABLE IF EXISTS NguoiDung;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE NguoiDung (
  NguoiDungID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  MaNguoiDung VARCHAR(30) NOT NULL,
  HoTen VARCHAR(150) NOT NULL,
  Email VARCHAR(150) NULL,
  MatKhauHash VARCHAR(255) NOT NULL,
  VaiTro ENUM('GIANG_VIEN','QUAN_LY','ADMIN') NOT NULL,
  LaGiangVien BOOLEAN NOT NULL DEFAULT FALSE,
  TrangThaiGiangDay ENUM('DANG_DAY','TAM_VANG','KHONG_AP_DUNG') NOT NULL,
  TrangThaiTaiKhoan ENUM('HOAT_DONG','BI_KHOA') NOT NULL DEFAULT 'HOAT_DONG',
  TaoLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CapNhatLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_nguoidung_ma UNIQUE (MaNguoiDung),
  CONSTRAINT uq_nguoidung_email UNIQUE (Email),
  CONSTRAINT ck_nguoidung_giangday CHECK (
    (LaGiangVien = TRUE AND TrangThaiGiangDay IN ('DANG_DAY','TAM_VANG'))
    OR (LaGiangVien = FALSE AND TrangThaiGiangDay = 'KHONG_AP_DUNG')
  )
) ENGINE=InnoDB;

CREATE TABLE ToaNha (
  ToaNhaID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  MaToa VARCHAR(20) NOT NULL,
  TenToa VARCHAR(100) NOT NULL,
  TrangThai ENUM('HOAT_DONG','NGUNG_SU_DUNG') NOT NULL DEFAULT 'HOAT_DONG',
  CONSTRAINT uq_toanha_ma UNIQUE (MaToa)
) ENGINE=InnoDB;

CREATE TABLE Phong (
  PhongID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ToaNhaID BIGINT UNSIGNED NOT NULL,
  MaPhong VARCHAR(30) NOT NULL,
  Tang SMALLINT NOT NULL,
  TenPhong VARCHAR(100) NULL,
  LoaiPhong ENUM('LY_THUYET','THUC_HANH','KHAC') NOT NULL,
  SucChua SMALLINT UNSIGNED NOT NULL,
  ChoPhepDat BOOLEAN NOT NULL DEFAULT FALSE,
  TrangThai ENUM('HOAT_DONG','TAM_NGUNG','NGUNG_SU_DUNG') NOT NULL DEFAULT 'HOAT_DONG',
  GhiChu VARCHAR(500) NULL,
  CONSTRAINT uq_phong_ma UNIQUE (MaPhong),
  CONSTRAINT fk_phong_toanha FOREIGN KEY (ToaNhaID) REFERENCES ToaNha(ToaNhaID) ON DELETE RESTRICT,
  CONSTRAINT ck_phong_succhua CHECK (SucChua > 0),
  INDEX idx_phong_search (TrangThai, ChoPhepDat, LoaiPhong, SucChua)
) ENGINE=InnoDB;

CREATE TABLE ThietBi (
  ThietBiID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  MaThietBi VARCHAR(30) NOT NULL,
  TenThietBi VARCHAR(100) NOT NULL,
  DonViTinh VARCHAR(30) NOT NULL,
  TrangThai ENUM('HOAT_DONG','NGUNG_SU_DUNG') NOT NULL DEFAULT 'HOAT_DONG',
  CONSTRAINT uq_thietbi_ma UNIQUE (MaThietBi)
) ENGINE=InnoDB;

CREATE TABLE PhongThietBi (
  PhongID BIGINT UNSIGNED NOT NULL,
  ThietBiID BIGINT UNSIGNED NOT NULL,
  SoLuongTot SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  SoLuongHong SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  CapNhatLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (PhongID, ThietBiID),
  CONSTRAINT fk_phongthietbi_phong FOREIGN KEY (PhongID) REFERENCES Phong(PhongID) ON DELETE RESTRICT,
  CONSTRAINT fk_phongthietbi_thietbi FOREIGN KEY (ThietBiID) REFERENCES ThietBi(ThietBiID) ON DELETE RESTRICT,
  INDEX idx_phongthietbi_search (ThietBiID, SoLuongTot, PhongID)
) ENGINE=InnoDB;

CREATE TABLE HocKy (
  HocKyID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  MaHocKy VARCHAR(30) NOT NULL,
  TenHocKy VARCHAR(100) NOT NULL,
  NgayBatDau DATE NOT NULL,
  NgayKetThuc DATE NOT NULL,
  TrangThai ENUM('NHAP','MO_DAT_PHONG','DONG') NOT NULL DEFAULT 'NHAP',
  DotImportHienHanhID BIGINT UNSIGNED NULL,
  SoGioBaoTruocTuDong SMALLINT UNSIGNED NOT NULL DEFAULT 24,
  SoNgayDatTruocToiDa SMALLINT UNSIGNED NOT NULL DEFAULT 30,
  SoTietToiDaMoiPhieu TINYINT UNSIGNED NOT NULL DEFAULT 5,
  SoPhieuHoatDongToiDaMoiGV SMALLINT UNSIGNED NOT NULL DEFAULT 8,
  TuanTamNghi TINYINT UNSIGNED NULL DEFAULT 8,
  TuanThiCuoiKy TINYINT UNSIGNED NULL DEFAULT 13,
  CONSTRAINT uq_hocky_ma UNIQUE (MaHocKy),
  CONSTRAINT ck_hocky_ngay CHECK (NgayBatDau <= NgayKetThuc),
  CONSTRAINT ck_hocky_sotiet CHECK (SoTietToiDaMoiPhieu BETWEEN 1 AND 13)
) ENGINE=InnoDB;

CREATE TABLE KhungTiet (
  KhungTietID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  HocKyID BIGINT UNSIGNED NOT NULL,
  SoTiet TINYINT UNSIGNED NOT NULL,
  GioBatDau TIME NOT NULL,
  GioKetThuc TIME NOT NULL,
  Buoi ENUM('SANG','CHIEU','TOI') NOT NULL,
  CONSTRAINT uq_khungtiet_hocky_tiet UNIQUE (HocKyID, SoTiet),
  CONSTRAINT fk_khungtiet_hocky FOREIGN KEY (HocKyID) REFERENCES HocKy(HocKyID) ON DELETE RESTRICT,
  CONSTRAINT ck_khungtiet_so CHECK (SoTiet BETWEEN 1 AND 13),
  CONSTRAINT ck_khungtiet_gio CHECK (GioBatDau < GioKetThuc)
) ENGINE=InnoDB;

CREATE TABLE NgayNghi (
  NgayNghiID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  HocKyID BIGINT UNSIGNED NOT NULL,
  Ngay DATE NOT NULL,
  LyDo VARCHAR(255) NOT NULL,
  CONSTRAINT uq_ngaynghi_hocky_ngay UNIQUE (HocKyID, Ngay),
  CONSTRAINT fk_ngaynghi_hocky FOREIGN KEY (HocKyID) REFERENCES HocKy(HocKyID) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE HocPhan (
  HocPhanID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  MaHocPhan VARCHAR(30) NOT NULL,
  TenHocPhan VARCHAR(150) NOT NULL,
  NhomDaoTao VARCHAR(50) NOT NULL,
  LoaiHocPhan ENUM('CHUYEN_NGANH','THONG_THUONG') NOT NULL,
  SoBuoiMoiTuanMacDinh TINYINT UNSIGNED NOT NULL DEFAULT 2,
  SoTietMoiBuoiMacDinh TINYINT UNSIGNED NOT NULL,
  SoTuanDayMacDinh TINYINT UNSIGNED NOT NULL DEFAULT 12,
  YeuCauThietBiJSON JSON NULL,
  TrangThai ENUM('HOAT_DONG','NGUNG_SU_DUNG') NOT NULL DEFAULT 'HOAT_DONG',
  CONSTRAINT uq_hocphan_ma UNIQUE (MaHocPhan),
  CONSTRAINT ck_hocphan_buoi CHECK (SoBuoiMoiTuanMacDinh > 0),
  CONSTRAINT ck_hocphan_tiet CHECK (SoTietMoiBuoiMacDinh BETWEEN 1 AND 13),
  CONSTRAINT ck_hocphan_tuan CHECK (SoTuanDayMacDinh > 0)
) ENGINE=InnoDB;

CREATE TABLE LopHocPhan (
  LopHocPhanID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  HocKyID BIGINT UNSIGNED NOT NULL,
  HocPhanID BIGINT UNSIGNED NOT NULL,
  MaLopHocPhan VARCHAR(50) NOT NULL,
  MaNhomSinhVien VARCHAR(100) NOT NULL,
  SiSo SMALLINT UNSIGNED NOT NULL,
  SoBuoiMoiTuan TINYINT UNSIGNED NOT NULL,
  SoTietMoiBuoi TINYINT UNSIGNED NOT NULL,
  SoTuanDay TINYINT UNSIGNED NOT NULL,
  LoaiBuoiMacDinh ENUM('LY_THUYET','THUC_HANH') NOT NULL,
  TrangThai ENUM('MO','DA_DONG') NOT NULL DEFAULT 'MO',
  CONSTRAINT uq_lophocphan_hocky_ma UNIQUE (HocKyID, MaLopHocPhan),
  CONSTRAINT fk_lophocphan_hocky FOREIGN KEY (HocKyID) REFERENCES HocKy(HocKyID) ON DELETE RESTRICT,
  CONSTRAINT fk_lophocphan_hocphan FOREIGN KEY (HocPhanID) REFERENCES HocPhan(HocPhanID) ON DELETE RESTRICT,
  CONSTRAINT ck_lophocphan_siso CHECK (SiSo > 0),
  CONSTRAINT ck_lophocphan_tiet CHECK (SoTietMoiBuoi BETWEEN 1 AND 13),
  INDEX idx_lophocphan_hocky (HocKyID, TrangThai)
) ENGINE=InnoDB;

CREATE TABLE PhanCongGiangDay (
  LopHocPhanID BIGINT UNSIGNED NOT NULL,
  GiangVienID BIGINT UNSIGNED NOT NULL,
  VaiTroGiangDay ENUM('CHINH','PHOI_HOP') NOT NULL DEFAULT 'CHINH',
  PRIMARY KEY (LopHocPhanID, GiangVienID),
  CONSTRAINT fk_phancong_lophocphan FOREIGN KEY (LopHocPhanID) REFERENCES LopHocPhan(LopHocPhanID) ON DELETE RESTRICT,
  CONSTRAINT fk_phancong_giangvien FOREIGN KEY (GiangVienID) REFERENCES NguoiDung(NguoiDungID) ON DELETE RESTRICT,
  INDEX idx_phancong_giangvien (GiangVienID, LopHocPhanID)
) ENGINE=InnoDB;

CREATE TABLE DotImportLich (
  DotImportLichID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  HocKyID BIGINT UNSIGNED NOT NULL,
  TenTep VARCHAR(255) NOT NULL,
  MaBamSHA256 CHAR(64) NOT NULL,
  TrangThai ENUM('DA_TAI_LEN','DA_KIEM_TRA','CO_LOI','DA_PHAT_HANH','BI_THAY_THE') NOT NULL,
  SoDong INT UNSIGNED NOT NULL DEFAULT 0,
  SoDongLoi INT UNSIGNED NOT NULL DEFAULT 0,
  BaoCaoLoiJSON JSON NULL,
  NguoiTaiID BIGINT UNSIGNED NOT NULL,
  TaiLenLuc DATETIME(6) NOT NULL,
  PhatHanhLuc DATETIME(6) NULL,
  CONSTRAINT fk_dotimport_hocky FOREIGN KEY (HocKyID) REFERENCES HocKy(HocKyID) ON DELETE RESTRICT,
  CONSTRAINT fk_dotimport_nguoidung FOREIGN KEY (NguoiTaiID) REFERENCES NguoiDung(NguoiDungID) ON DELETE RESTRICT,
  INDEX idx_dotimport_hocky (HocKyID, TrangThai, TaiLenLuc)
) ENGINE=InnoDB;

ALTER TABLE HocKy
  ADD CONSTRAINT fk_hocky_dotimport_hienhanh
  FOREIGN KEY (DotImportHienHanhID) REFERENCES DotImportLich(DotImportLichID) ON DELETE RESTRICT;

CREATE TABLE LichChinhThuc (
  LichChinhThucID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  DotImportLichID BIGINT UNSIGNED NOT NULL,
  MaDong VARCHAR(50) NOT NULL,
  Ngay DATE NOT NULL,
  PhongID BIGINT UNSIGNED NOT NULL,
  TietBatDau TINYINT UNSIGNED NOT NULL,
  TietKetThuc TINYINT UNSIGNED NOT NULL,
  LoaiHoatDong ENUM('LICH_HOC','LICH_THI','SU_KIEN','BAN_NGOAI_KHOA') NOT NULL,
  LopHocPhanID BIGINT UNSIGNED NULL,
  GiangVienID BIGINT UNSIGNED NULL,
  SiSo SMALLINT UNSIGNED NULL,
  TenHoatDong VARCHAR(200) NOT NULL,
  LoaiBuoi ENUM('LY_THUYET','THUC_HANH','THI','SU_KIEN','KHAC') NOT NULL,
  GhiChu VARCHAR(500) NULL,
  TrangThai ENUM('NHAP','HOAT_DONG','BI_THAY_THE','DA_GIAI_PHONG','CAN_BO_TRI_LAI') NOT NULL,
  LyDoCanBoTriLai VARCHAR(500) NULL,
  CONSTRAINT uq_lich_dotimport_madong UNIQUE (DotImportLichID, MaDong),
  CONSTRAINT fk_lich_dotimport FOREIGN KEY (DotImportLichID) REFERENCES DotImportLich(DotImportLichID) ON DELETE RESTRICT,
  CONSTRAINT fk_lich_phong FOREIGN KEY (PhongID) REFERENCES Phong(PhongID) ON DELETE RESTRICT,
  CONSTRAINT fk_lich_lophocphan FOREIGN KEY (LopHocPhanID) REFERENCES LopHocPhan(LopHocPhanID) ON DELETE RESTRICT,
  CONSTRAINT fk_lich_giangvien FOREIGN KEY (GiangVienID) REFERENCES NguoiDung(NguoiDungID) ON DELETE RESTRICT,
  CONSTRAINT ck_lich_tiet CHECK (TietBatDau BETWEEN 1 AND 13 AND TietKetThuc BETWEEN TietBatDau AND 13),
  CONSTRAINT ck_lich_siso CHECK (SiSo IS NULL OR SiSo > 0),
  CONSTRAINT ck_lich_hoc_fields CHECK (
    (LoaiHoatDong = 'LICH_HOC' AND LopHocPhanID IS NOT NULL AND GiangVienID IS NOT NULL AND SiSo IS NOT NULL)
    OR LoaiHoatDong <> 'LICH_HOC'
  ),
  INDEX idx_lich_phong_ngay (PhongID, Ngay, TrangThai),
  INDEX idx_lich_giangvien (Ngay, GiangVienID, TrangThai, TietBatDau, TietKetThuc),
  INDEX idx_lich_lop (Ngay, LopHocPhanID, TrangThai, TietBatDau, TietKetThuc)
) ENGINE=InnoDB;

CREATE TABLE PhieuDatPhong (
  PhieuDatPhongID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  MaPhieu VARCHAR(30) NOT NULL,
  MaGui CHAR(36) NOT NULL,
  HocKyID BIGINT UNSIGNED NOT NULL,
  NguoiYeuCauID BIGINT UNSIGNED NOT NULL,
  LopHocPhanID BIGINT UNSIGNED NULL,
  Ngay DATE NOT NULL,
  TietBatDau TINYINT UNSIGNED NOT NULL,
  TietKetThuc TINYINT UNSIGNED NOT NULL,
  MucDich ENUM('HOC_NHOM','HUONG_DAN','DAY_BU','THUC_HANH_HAI_PHONG','SU_KIEN','KHAC') NOT NULL,
  SoNguoi SMALLINT UNSIGNED NOT NULL,
  LoaiPhongYeuCau ENUM('LY_THUYET','THUC_HANH','BAT_KY') NOT NULL,
  YeuCauThietBiJSON JSON NULL,
  GhiChu VARCHAR(500) NULL,
  TrangThai ENUM('MOI','CHO_DUYET','TU_DONG_XAC_NHAN','DA_DUYET','BI_TU_CHOI','DA_HUY','CAN_BO_TRI_LAI') NOT NULL,
  LyDoChuyenDuyet VARCHAR(255) NULL,
  LyDoTuChoi VARCHAR(500) NULL,
  NguoiXuLyID BIGINT UNSIGNED NULL,
  XuLyLuc DATETIME(6) NULL,
  TaoLuc DATETIME(6) NOT NULL,
  CapNhatLuc DATETIME(6) NOT NULL,
  CONSTRAINT uq_phieu_ma UNIQUE (MaPhieu),
  CONSTRAINT uq_phieu_magui UNIQUE (MaGui),
  CONSTRAINT fk_phieu_hocky FOREIGN KEY (HocKyID) REFERENCES HocKy(HocKyID) ON DELETE RESTRICT,
  CONSTRAINT fk_phieu_nguoiyc FOREIGN KEY (NguoiYeuCauID) REFERENCES NguoiDung(NguoiDungID) ON DELETE RESTRICT,
  CONSTRAINT fk_phieu_lophocphan FOREIGN KEY (LopHocPhanID) REFERENCES LopHocPhan(LopHocPhanID) ON DELETE RESTRICT,
  CONSTRAINT fk_phieu_nguoixuly FOREIGN KEY (NguoiXuLyID) REFERENCES NguoiDung(NguoiDungID) ON DELETE RESTRICT,
  CONSTRAINT ck_phieu_tiet CHECK (TietBatDau BETWEEN 1 AND 13 AND TietKetThuc BETWEEN TietBatDau AND 13),
  CONSTRAINT ck_phieu_songuoi CHECK (SoNguoi > 0),
  INDEX idx_phieu_nguoiyc (Ngay, NguoiYeuCauID, TrangThai, TietBatDau, TietKetThuc),
  INDEX idx_phieu_lop (Ngay, LopHocPhanID, TrangThai, TietBatDau, TietKetThuc),
  INDEX idx_phieu_status (TrangThai, TaoLuc)
) ENGINE=InnoDB;

CREATE TABLE PhieuDatPhongPhong (
  PhieuDatPhongID BIGINT UNSIGNED NOT NULL,
  PhongID BIGINT UNSIGNED NOT NULL,
  SoNguoiDuKien SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (PhieuDatPhongID, PhongID),
  CONSTRAINT fk_phieuphong_phieu FOREIGN KEY (PhieuDatPhongID) REFERENCES PhieuDatPhong(PhieuDatPhongID) ON DELETE RESTRICT,
  CONSTRAINT fk_phieuphong_phong FOREIGN KEY (PhongID) REFERENCES Phong(PhongID) ON DELETE RESTRICT,
  CONSTRAINT ck_phieuphong_songuoi CHECK (SoNguoiDuKien > 0),
  INDEX idx_phieuphong_phong (PhongID, PhieuDatPhongID)
) ENGINE=InnoDB;

CREATE TABLE SlotPhong (
  PhongID BIGINT UNSIGNED NOT NULL,
  Ngay DATE NOT NULL,
  SoTiet TINYINT UNSIGNED NOT NULL,
  LoaiNguon ENUM('LICH_CHINH_THUC','PHIEU_DAT_PHONG') NOT NULL,
  LichChinhThucID BIGINT UNSIGNED NULL,
  PhieuDatPhongID BIGINT UNSIGNED NULL,
  TaoLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (PhongID, Ngay, SoTiet),
  CONSTRAINT fk_slot_phong FOREIGN KEY (PhongID) REFERENCES Phong(PhongID) ON DELETE RESTRICT,
  CONSTRAINT fk_slot_lich FOREIGN KEY (LichChinhThucID) REFERENCES LichChinhThuc(LichChinhThucID) ON DELETE RESTRICT,
  CONSTRAINT fk_slot_phieu FOREIGN KEY (PhieuDatPhongID) REFERENCES PhieuDatPhong(PhieuDatPhongID) ON DELETE RESTRICT,
  CONSTRAINT ck_slot_tiet CHECK (SoTiet BETWEEN 1 AND 13),
  CONSTRAINT ck_slot_nguon CHECK (
    (LoaiNguon = 'LICH_CHINH_THUC' AND LichChinhThucID IS NOT NULL AND PhieuDatPhongID IS NULL)
    OR (LoaiNguon = 'PHIEU_DAT_PHONG' AND PhieuDatPhongID IS NOT NULL AND LichChinhThucID IS NULL)
  ),
  INDEX idx_slot_ngay (Ngay, SoTiet, PhongID),
  INDEX idx_slot_lich (LichChinhThucID),
  INDEX idx_slot_phieu (PhieuDatPhongID)
) ENGINE=InnoDB;

CREATE TABLE YeuCauGiaiPhongLich (
  YeuCauGiaiPhongLichID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  LichChinhThucID BIGINT UNSIGNED NOT NULL,
  NguoiYeuCauID BIGINT UNSIGNED NOT NULL,
  LyDo VARCHAR(500) NOT NULL,
  TrangThai ENUM('CHO_DUYET','DA_XAC_NHAN','BI_TU_CHOI') NOT NULL,
  NguoiXuLyID BIGINT UNSIGNED NULL,
  LyDoXuLy VARCHAR(500) NULL,
  TaoLuc DATETIME(6) NOT NULL,
  XuLyLuc DATETIME(6) NULL,
  CONSTRAINT uq_giaiphong_lich UNIQUE (LichChinhThucID),
  CONSTRAINT fk_giaiphong_lich FOREIGN KEY (LichChinhThucID) REFERENCES LichChinhThuc(LichChinhThucID) ON DELETE RESTRICT,
  CONSTRAINT fk_giaiphong_nguoiyc FOREIGN KEY (NguoiYeuCauID) REFERENCES NguoiDung(NguoiDungID) ON DELETE RESTRICT,
  CONSTRAINT fk_giaiphong_nguoixuly FOREIGN KEY (NguoiXuLyID) REFERENCES NguoiDung(NguoiDungID) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE PhongBiKhoa (
  PhongBiKhoaID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  PhongID BIGINT UNSIGNED NOT NULL,
  TuNgay DATE NOT NULL,
  DenNgay DATE NOT NULL,
  TietBatDau TINYINT UNSIGNED NULL,
  TietKetThuc TINYINT UNSIGNED NULL,
  Loai ENUM('BAO_TRI','SU_CO') NOT NULL,
  MucDo ENUM('KE_HOACH','KHAN_CAP') NOT NULL,
  LyDo VARCHAR(500) NOT NULL,
  TrangThai ENUM('HOAT_DONG','KET_THUC','DA_HUY') NOT NULL,
  NguoiTaoID BIGINT UNSIGNED NOT NULL,
  TaoLuc DATETIME(6) NOT NULL,
  KetThucLuc DATETIME(6) NULL,
  CONSTRAINT fk_phongbikhoa_phong FOREIGN KEY (PhongID) REFERENCES Phong(PhongID) ON DELETE RESTRICT,
  CONSTRAINT fk_phongbikhoa_nguoitao FOREIGN KEY (NguoiTaoID) REFERENCES NguoiDung(NguoiDungID) ON DELETE RESTRICT,
  CONSTRAINT ck_phongbikhoa_ngay CHECK (TuNgay <= DenNgay),
  CONSTRAINT ck_phongbikhoa_tiet CHECK (
    (TietBatDau IS NULL AND TietKetThuc IS NULL)
    OR (TietBatDau BETWEEN 1 AND 13 AND TietKetThuc BETWEEN TietBatDau AND 13)
  ),
  INDEX idx_phongbikhoa_search (PhongID, TrangThai, TuNgay, DenNgay)
) ENGINE=InnoDB;

CREATE TABLE ThongBao (
  ThongBaoID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NguoiNhanID BIGINT UNSIGNED NOT NULL,
  TieuDe VARCHAR(200) NOT NULL,
  NoiDung TEXT NOT NULL,
  LoaiDoiTu ENUM('PHIEU','LICH','GIAI_PHONG','KHOA_PHONG','IMPORT') NOT NULL,
  DoiTuID BIGINT UNSIGNED NOT NULL,
  DaDoc BOOLEAN NOT NULL DEFAULT FALSE,
  TaoLuc DATETIME(6) NOT NULL,
  DocLuc DATETIME(6) NULL,
  CONSTRAINT fk_thongbao_nguoinhan FOREIGN KEY (NguoiNhanID) REFERENCES NguoiDung(NguoiDungID) ON DELETE RESTRICT,
  INDEX idx_thongbao_inbox (NguoiNhanID, DaDoc, TaoLuc)
) ENGINE=InnoDB;

CREATE TABLE NhatKyHeThong (
  NhatKyHeThongID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NguoiThucHienID BIGINT UNSIGNED NULL,
  HanhDong VARCHAR(50) NOT NULL,
  LoaiDoiTu VARCHAR(50) NOT NULL,
  DoiTuID VARCHAR(50) NOT NULL,
  DuLieuTruocJSON JSON NULL,
  DuLieuSauJSON JSON NULL,
  DiaChiIP VARCHAR(45) NULL,
  TaoLuc DATETIME(6) NOT NULL,
  CONSTRAINT fk_nhatky_nguoidung FOREIGN KEY (NguoiThucHienID) REFERENCES NguoiDung(NguoiDungID) ON DELETE RESTRICT,
  INDEX idx_nhatky_object (LoaiDoiTu, DoiTuID, TaoLuc)
) ENGINE=InnoDB;
