-- Mini OTA nhiều cơ sở lưu trú - schema MVP 22 bảng.
-- Mục tiêu: MySQL 8.x và MariaDB 10.4.x, utf8mb4, InnoDB.

SET NAMES utf8mb4;
CREATE DATABASE IF NOT EXISTS hotel_booking CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE hotel_booking;
SET FOREIGN_KEY_CHECKS = 0;

-- Chỉ xóa các bảng của ứng dụng trong database chuyên biệt; không DROP DATABASE.
DROP TABLE IF EXISTS NhatKyHeThong, DanhGia, YeuCauHuyMienPhi, ThanhToan,
  GiuTonPhongDem, GiaDemDatCho, HangMucDatCho, DatCho, XemTruocDatCho,
  TonPhongNgay, KhuyenMai, GiaPhongNgay, SanPhamPhong, ChinhSachHuy,
  LoaiPhongTienNghi, CoSoTienNghi, LoaiPhong, CoSoLuuTru, TienNghi,
  ThanhVienDoiTac, ToChucDoiTac, NguoiDung;

-- Dọn các bảng của schema 38 bảng cũ nếu đang nâng cấp tại chỗ.
DROP TABLE IF EXISTS BoNhoDemGooglePlaces, DoiChieuGooglePlaces, ThongBao,
  HoanTien, LanThanhToan, DieuChinhDatCho, KhachLuuTru, XemTruocHangMuc,
  KhuyenMaiSanPham, GoiGia, GoiBuaAn, ThuePhiCoSo, AnhLoaiPhong, AnhCoSo,
  LoaiCoSo, ThanhPho;

CREATE TABLE NguoiDung (
  NguoiDungID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  MaNguoiDung VARCHAR(24) NOT NULL,
  HoTen VARCHAR(150) NOT NULL,
  Email VARCHAR(190) NOT NULL,
  SoDienThoai VARCHAR(20) NULL,
  MatKhauHash VARCHAR(255) NOT NULL,
  VaiTro VARCHAR(16) NOT NULL,
  TrangThai VARCHAR(16) NOT NULL DEFAULT 'HOAT_DONG',
  TaoLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CapNhatLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY UQ_NguoiDung_Ma (MaNguoiDung),
  UNIQUE KEY UQ_NguoiDung_Email (Email),
  CONSTRAINT CK_NguoiDung_VaiTro CHECK (VaiTro IN ('CUSTOMER','PARTNER','ADMIN')),
  CONSTRAINT CK_NguoiDung_TrangThai CHECK (TrangThai IN ('HOAT_DONG','KHOA'))
) ENGINE=InnoDB;

CREATE TABLE ToChucDoiTac (
  ToChucDoiTacID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  MaToChuc VARCHAR(24) NOT NULL,
  TenToChuc VARCHAR(190) NOT NULL,
  EmailLienHe VARCHAR(190) NOT NULL,
  SoDienThoai VARCHAR(20) NULL,
  TrangThai VARCHAR(16) NOT NULL DEFAULT 'HOAT_DONG',
  TaoLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY UQ_ToChuc_Ma (MaToChuc),
  CONSTRAINT CK_ToChuc_TrangThai CHECK (TrangThai IN ('HOAT_DONG','TAM_KHOA'))
) ENGINE=InnoDB;

CREATE TABLE ThanhVienDoiTac (
  ToChucDoiTacID BIGINT UNSIGNED NOT NULL,
  NguoiDungID BIGINT UNSIGNED NOT NULL,
  LaChuSoHuu TINYINT(1) NOT NULL DEFAULT 0,
  TaoLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (ToChucDoiTacID, NguoiDungID),
  UNIQUE KEY UQ_ThanhVien_NguoiDung (NguoiDungID),
  CONSTRAINT FK_ThanhVien_ToChuc FOREIGN KEY (ToChucDoiTacID) REFERENCES ToChucDoiTac(ToChucDoiTacID),
  CONSTRAINT FK_ThanhVien_NguoiDung FOREIGN KEY (NguoiDungID) REFERENCES NguoiDung(NguoiDungID)
) ENGINE=InnoDB;

CREATE TABLE TienNghi (
  TienNghiID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  MaTienNghi VARCHAR(40) NOT NULL,
  TenTienNghi VARCHAR(120) NOT NULL,
  PhamVi VARCHAR(12) NOT NULL,
  TrangThai VARCHAR(16) NOT NULL DEFAULT 'HOAT_DONG',
  UNIQUE KEY UQ_TienNghi_Ma (MaTienNghi),
  CONSTRAINT CK_TienNghi_PhamVi CHECK (PhamVi IN ('PROPERTY','ROOM')),
  CONSTRAINT CK_TienNghi_TrangThai CHECK (TrangThai IN ('HOAT_DONG','NGUNG'))
) ENGINE=InnoDB;

CREATE TABLE CoSoLuuTru (
  CoSoLuuTruID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  MaCoSo VARCHAR(24) NOT NULL,
  ToChucDoiTacID BIGINT UNSIGNED NOT NULL,
  MaThanhPho CHAR(3) NOT NULL DEFAULT 'HCM',
  LoaiCoSo VARCHAR(20) NOT NULL,
  TenCoSo VARCHAR(190) NOT NULL,
  TenTrongNguon VARCHAR(255) NOT NULL,
  NguonTen VARCHAR(80) NOT NULL,
  MaBanGhiNguon VARCHAR(80) NOT NULL,
  Slug VARCHAR(220) NOT NULL,
  DiaChi VARCHAR(500) NOT NULL,
  NguonDiaChi VARCHAR(80) NOT NULL,
  DiaChiXacMinhLuc DATETIME(6) NOT NULL,
  MoTa TEXT NULL,
  AnhJSON JSON NOT NULL,
  GooglePlaceID VARCHAR(255) NULL,
  GoogleMatchStatus VARCHAR(16) NOT NULL DEFAULT 'NOT_CHECKED',
  GoogleVerifiedAt DATETIME(6) NULL,
  ViDo DECIMAL(10,7) NULL,
  KinhDo DECIMAL(10,7) NULL,
  NguonToaDo VARCHAR(40) NULL,
  ToaDoXacMinhLuc DATETIME(6) NULL,
  TrangThaiDoiChieu VARCHAR(32) NOT NULL,
  DuongDanBanDo VARCHAR(1000) NULL,
  SoSao DECIMAL(2,1) NULL,
  TyLeThue DECIMAL(5,2) NOT NULL DEFAULT 0,
  ThueDaBaoGom TINYINT(1) NOT NULL DEFAULT 1,
  TyLePhiDichVu DECIMAL(5,2) NOT NULL DEFAULT 0,
  PhiDichVuDaBaoGom TINYINT(1) NOT NULL DEFAULT 1,
  GioNhanPhong TIME NOT NULL DEFAULT '14:00:00',
  GioTraPhong TIME NOT NULL DEFAULT '12:00:00',
  MuiGio VARCHAR(64) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
  TrangThai VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  NguoiDuyetID BIGINT UNSIGNED NULL,
  DuyetLuc DATETIME(6) NULL,
  GhiChuDuyet VARCHAR(1000) NULL,
  TaoLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CapNhatLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY UQ_CoSo_Ma (MaCoSo),
  UNIQUE KEY UQ_CoSo_Slug (Slug),
  UNIQUE KEY UQ_CoSo_Nguon (NguonTen, MaBanGhiNguon),
  UNIQUE KEY UQ_CoSo_GooglePlace (GooglePlaceID),
  KEY IX_CoSo_TimKiem (MaThanhPho, TrangThai, LoaiCoSo),
  KEY IX_CoSo_ToChuc (ToChucDoiTacID, TrangThai),
  CONSTRAINT FK_CoSo_ToChuc FOREIGN KEY (ToChucDoiTacID) REFERENCES ToChucDoiTac(ToChucDoiTacID),
  CONSTRAINT FK_CoSo_NguoiDuyet FOREIGN KEY (NguoiDuyetID) REFERENCES NguoiDung(NguoiDungID),
  CONSTRAINT CK_CoSo_ThanhPho CHECK (MaThanhPho = 'HCM'),
  CONSTRAINT CK_CoSo_Loai CHECK (LoaiCoSo IN ('HOTEL','RESORT','APARTMENT','VILLA','HOSTEL','GUEST_HOUSE')),
  CONSTRAINT CK_CoSo_GoogleStatus CHECK (GoogleMatchStatus IN ('NOT_CHECKED','MATCHED','AMBIGUOUS','NOT_FOUND')),
  CONSTRAINT CK_CoSo_GoogleMetadata CHECK (
    (GoogleMatchStatus = 'NOT_CHECKED' AND GooglePlaceID IS NULL AND GoogleVerifiedAt IS NULL) OR
    (GoogleMatchStatus = 'MATCHED' AND GooglePlaceID IS NOT NULL AND GoogleVerifiedAt IS NOT NULL) OR
    (GoogleMatchStatus IN ('AMBIGUOUS','NOT_FOUND') AND GooglePlaceID IS NULL AND GoogleVerifiedAt IS NOT NULL)
  ),
  CONSTRAINT CK_CoSo_ToaDo CHECK (
    (ViDo IS NULL AND KinhDo IS NULL AND NguonToaDo IS NULL AND ToaDoXacMinhLuc IS NULL) OR
    (ViDo IS NOT NULL AND KinhDo IS NOT NULL AND NguonToaDo IS NOT NULL AND ToaDoXacMinhLuc IS NOT NULL
      AND ViDo BETWEEN -90 AND 90 AND KinhDo BETWEEN -180 AND 180)
  ),
  CONSTRAINT CK_CoSo_Sao CHECK (SoSao IS NULL OR SoSao BETWEEN 0 AND 5),
  CONSTRAINT CK_CoSo_ThuePhi CHECK (TyLeThue BETWEEN 0 AND 100 AND TyLePhiDichVu BETWEEN 0 AND 100),
  CONSTRAINT CK_CoSo_TrangThai CHECK (TrangThai IN ('DRAFT','PENDING_REVIEW','ACTIVE','REJECTED','SUSPENDED')),
  CONSTRAINT CK_CoSo_Duyet CHECK (
    (TrangThai IN ('ACTIVE','REJECTED','SUSPENDED') AND NguoiDuyetID IS NOT NULL AND DuyetLuc IS NOT NULL) OR
    (TrangThai IN ('DRAFT','PENDING_REVIEW') AND NguoiDuyetID IS NULL AND DuyetLuc IS NULL)
  )
) ENGINE=InnoDB;

CREATE TABLE LoaiPhong (
  LoaiPhongID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CoSoLuuTruID BIGINT UNSIGNED NOT NULL,
  MaLoaiPhong VARCHAR(24) NOT NULL,
  TenLoaiPhong VARCHAR(150) NOT NULL,
  MoTa TEXT NULL,
  SoKhachToiDa SMALLINT UNSIGNED NOT NULL,
  SoNguoiLonToiDa SMALLINT UNSIGNED NOT NULL,
  SoTreEmToiDa SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  CauHinhGiuongJSON JSON NOT NULL,
  DienTichM2 DECIMAL(7,2) NULL,
  ChoPhepHutThuoc TINYINT(1) NOT NULL DEFAULT 0,
  AnhJSON JSON NOT NULL,
  TrangThai VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
  TaoLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CapNhatLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY UQ_LoaiPhong_Ma (CoSoLuuTruID, MaLoaiPhong),
  KEY IX_LoaiPhong_CoSoTrangThai (CoSoLuuTruID, TrangThai),
  CONSTRAINT FK_LoaiPhong_CoSo FOREIGN KEY (CoSoLuuTruID) REFERENCES CoSoLuuTru(CoSoLuuTruID),
  CONSTRAINT CK_LoaiPhong_SucChua CHECK (SoKhachToiDa > 0 AND SoNguoiLonToiDa > 0 AND SoNguoiLonToiDa <= SoKhachToiDa AND SoTreEmToiDa <= SoKhachToiDa),
  CONSTRAINT CK_LoaiPhong_DienTich CHECK (DienTichM2 IS NULL OR DienTichM2 > 0),
  CONSTRAINT CK_LoaiPhong_TrangThai CHECK (TrangThai IN ('ACTIVE','INACTIVE'))
) ENGINE=InnoDB;

CREATE TABLE CoSoTienNghi (
  CoSoLuuTruID BIGINT UNSIGNED NOT NULL,
  TienNghiID BIGINT UNSIGNED NOT NULL,
  MienPhi TINYINT(1) NOT NULL DEFAULT 1,
  GhiChu VARCHAR(255) NULL,
  PRIMARY KEY (CoSoLuuTruID, TienNghiID),
  CONSTRAINT FK_CoSoTienNghi_CoSo FOREIGN KEY (CoSoLuuTruID) REFERENCES CoSoLuuTru(CoSoLuuTruID),
  CONSTRAINT FK_CoSoTienNghi_TienNghi FOREIGN KEY (TienNghiID) REFERENCES TienNghi(TienNghiID)
) ENGINE=InnoDB;

CREATE TABLE LoaiPhongTienNghi (
  LoaiPhongID BIGINT UNSIGNED NOT NULL,
  TienNghiID BIGINT UNSIGNED NOT NULL,
  SoLuong SMALLINT UNSIGNED NULL,
  GhiChu VARCHAR(255) NULL,
  PRIMARY KEY (LoaiPhongID, TienNghiID),
  CONSTRAINT FK_LoaiPhongTienNghi_Phong FOREIGN KEY (LoaiPhongID) REFERENCES LoaiPhong(LoaiPhongID),
  CONSTRAINT FK_LoaiPhongTienNghi_TienNghi FOREIGN KEY (TienNghiID) REFERENCES TienNghi(TienNghiID),
  CONSTRAINT CK_LoaiPhongTienNghi_SoLuong CHECK (SoLuong IS NULL OR SoLuong > 0)
) ENGINE=InnoDB;

CREATE TABLE ChinhSachHuy (
  ChinhSachHuyID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CoSoLuuTruID BIGINT UNSIGNED NOT NULL,
  MaChinhSach VARCHAR(24) NOT NULL,
  TenChinhSach VARCHAR(150) NOT NULL,
  LoaiChinhSach VARCHAR(20) NOT NULL,
  SoGioHuyMienPhi SMALLINT UNSIGNED NULL,
  LoaiPhat VARCHAR(20) NOT NULL,
  GiaTriPhat DECIMAL(12,2) NOT NULL,
  TyLePhatNoShow DECIMAL(5,2) NOT NULL DEFAULT 100,
  TrangThai VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
  UNIQUE KEY UQ_ChinhSachHuy_Ma (CoSoLuuTruID, MaChinhSach),
  CONSTRAINT FK_ChinhSachHuy_CoSo FOREIGN KEY (CoSoLuuTruID) REFERENCES CoSoLuuTru(CoSoLuuTruID),
  CONSTRAINT CK_ChinhSachHuy_Loai CHECK (LoaiChinhSach IN ('FLEXIBLE','NON_REFUNDABLE')),
  CONSTRAINT CK_ChinhSachHuy_Phat CHECK (LoaiPhat IN ('NONE','PERCENT','FIRST_NIGHT','FULL_STAY') AND GiaTriPhat BETWEEN 0 AND 100),
  CONSTRAINT CK_ChinhSachHuy_NoShow CHECK (TyLePhatNoShow BETWEEN 0 AND 100),
  CONSTRAINT CK_ChinhSachHuy_TrangThai CHECK (TrangThai IN ('ACTIVE','INACTIVE'))
) ENGINE=InnoDB;

CREATE TABLE SanPhamPhong (
  SanPhamPhongID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  LoaiPhongID BIGINT UNSIGNED NOT NULL,
  ChinhSachHuyID BIGINT UNSIGNED NOT NULL,
  MaSanPham VARCHAR(24) NOT NULL,
  TenSanPham VARCHAR(150) NOT NULL,
  LoaiBuaAn VARCHAR(24) NOT NULL,
  ThoiDiemThanhToan VARCHAR(24) NOT NULL,
  TrangThai VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
  UNIQUE KEY UQ_SanPhamPhong_Ma (LoaiPhongID, MaSanPham),
  KEY IX_SanPhamPhong_PhongTrangThai (LoaiPhongID, TrangThai),
  CONSTRAINT FK_SanPhamPhong_Phong FOREIGN KEY (LoaiPhongID) REFERENCES LoaiPhong(LoaiPhongID),
  CONSTRAINT FK_SanPhamPhong_ChinhSach FOREIGN KEY (ChinhSachHuyID) REFERENCES ChinhSachHuy(ChinhSachHuyID),
  CONSTRAINT CK_SanPhamPhong_BuaAn CHECK (LoaiBuaAn IN ('ROOM_ONLY','BREAKFAST_INCLUDED','HALF_BOARD')),
  CONSTRAINT CK_SanPhamPhong_ThanhToan CHECK (ThoiDiemThanhToan IN ('PAY_AT_PROPERTY','PAY_ONLINE')),
  CONSTRAINT CK_SanPhamPhong_TrangThai CHECK (TrangThai IN ('ACTIVE','INACTIVE'))
) ENGINE=InnoDB;

CREATE TABLE GiaPhongNgay (
  SanPhamPhongID BIGINT UNSIGNED NOT NULL,
  NgayLuuTru DATE NOT NULL,
  GiaCoBan DECIMAL(14,2) NOT NULL,
  DongBan TINYINT(1) NOT NULL DEFAULT 0,
  SoDemToiThieu TINYINT UNSIGNED NOT NULL DEFAULT 1,
  SoDemToiDa TINYINT UNSIGNED NULL,
  SoNgayDatTruoc SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  PhienBan INT UNSIGNED NOT NULL DEFAULT 1,
  CapNhatLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (SanPhamPhongID, NgayLuuTru),
  KEY IX_GiaPhongNgay_Ngay (NgayLuuTru, DongBan, SanPhamPhongID),
  CONSTRAINT FK_GiaPhongNgay_SanPham FOREIGN KEY (SanPhamPhongID) REFERENCES SanPhamPhong(SanPhamPhongID),
  CONSTRAINT CK_GiaPhongNgay_Gia CHECK (GiaCoBan > 0),
  CONSTRAINT CK_GiaPhongNgay_SoDem CHECK (SoDemToiThieu BETWEEN 1 AND 30 AND (SoDemToiDa IS NULL OR (SoDemToiDa BETWEEN SoDemToiThieu AND 30))),
  CONSTRAINT CK_GiaPhongNgay_DatTruoc CHECK (SoNgayDatTruoc <= 730),
  CONSTRAINT CK_GiaPhongNgay_PhienBan CHECK (PhienBan >= 1)
) ENGINE=InnoDB;

CREATE TABLE KhuyenMai (
  KhuyenMaiID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CoSoLuuTruID BIGINT UNSIGNED NOT NULL,
  MaKhuyenMai VARCHAR(24) NOT NULL,
  TenKhuyenMai VARCHAR(150) NOT NULL,
  PhanTramGiam DECIMAL(5,2) NOT NULL,
  DatTu DATETIME(6) NOT NULL,
  DatDen DATETIME(6) NOT NULL,
  LuuTruTu DATE NOT NULL,
  LuuTruDen DATE NOT NULL,
  TrangThai VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
  UNIQUE KEY UQ_KhuyenMai_Ma (CoSoLuuTruID, MaKhuyenMai),
  KEY IX_KhuyenMai_ApDung (CoSoLuuTruID, TrangThai, DatTu, DatDen, LuuTruTu, LuuTruDen),
  CONSTRAINT FK_KhuyenMai_CoSo FOREIGN KEY (CoSoLuuTruID) REFERENCES CoSoLuuTru(CoSoLuuTruID),
  CONSTRAINT CK_KhuyenMai_Giam CHECK (PhanTramGiam > 0 AND PhanTramGiam <= 100),
  CONSTRAINT CK_KhuyenMai_CuaSo CHECK (DatTu <= DatDen AND LuuTruTu <= LuuTruDen),
  CONSTRAINT CK_KhuyenMai_TrangThai CHECK (TrangThai IN ('ACTIVE','INACTIVE'))
) ENGINE=InnoDB;

CREATE TABLE TonPhongNgay (
  LoaiPhongID BIGINT UNSIGNED NOT NULL,
  NgayLuuTru DATE NOT NULL,
  TongSoLuong SMALLINT UNSIGNED NOT NULL,
  SoLuongDaGiu SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  PhienBan INT UNSIGNED NOT NULL DEFAULT 1,
  CapNhatLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (LoaiPhongID, NgayLuuTru),
  KEY IX_TonPhongNgay_Ngay (NgayLuuTru, LoaiPhongID),
  CONSTRAINT FK_TonPhongNgay_Phong FOREIGN KEY (LoaiPhongID) REFERENCES LoaiPhong(LoaiPhongID),
  CONSTRAINT CK_TonPhongNgay_SoLuong CHECK (SoLuongDaGiu <= TongSoLuong),
  CONSTRAINT CK_TonPhongNgay_PhienBan CHECK (PhienBan >= 1)
) ENGINE=InnoDB;

CREATE TABLE XemTruocDatCho (
  XemTruocDatChoID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  TokenHash CHAR(64) NOT NULL,
  KhachHangID BIGINT UNSIGNED NOT NULL,
  CoSoLuuTruID BIGINT UNSIGNED NOT NULL,
  NgayNhanPhong DATE NOT NULL,
  NgayTraPhong DATE NOT NULL,
  TienTe CHAR(3) NOT NULL DEFAULT 'VND',
  TongTien DECIMAL(14,2) NOT NULL,
  SoTienTraNgay DECIMAL(14,2) NOT NULL DEFAULT 0,
  SoTienTraTaiCoSo DECIMAL(14,2) NOT NULL DEFAULT 0,
  PhanBoJSON JSON NOT NULL,
  Fingerprint CHAR(64) NOT NULL,
  TrangThai VARCHAR(16) NOT NULL DEFAULT 'VALID',
  HetHanLuc DATETIME(6) NOT NULL,
  TaoLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  DaDungLuc DATETIME(6) NULL,
  UNIQUE KEY UQ_XemTruoc_Token (TokenHash),
  KEY IX_XemTruoc_Khach (KhachHangID, TrangThai, HetHanLuc),
  CONSTRAINT FK_XemTruoc_Khach FOREIGN KEY (KhachHangID) REFERENCES NguoiDung(NguoiDungID),
  CONSTRAINT FK_XemTruoc_CoSo FOREIGN KEY (CoSoLuuTruID) REFERENCES CoSoLuuTru(CoSoLuuTruID),
  CONSTRAINT CK_XemTruoc_Ngay CHECK (NgayNhanPhong < NgayTraPhong),
  CONSTRAINT CK_XemTruoc_Tien CHECK (TongTien >= 0 AND SoTienTraNgay >= 0 AND SoTienTraTaiCoSo >= 0 AND TongTien = SoTienTraNgay + SoTienTraTaiCoSo),
  CONSTRAINT CK_XemTruoc_TienTe CHECK (TienTe = 'VND'),
  CONSTRAINT CK_XemTruoc_TrangThai CHECK (TrangThai IN ('VALID','USED','INVALIDATED')),
  CONSTRAINT CK_XemTruoc_DaDung CHECK ((TrangThai = 'USED' AND DaDungLuc IS NOT NULL) OR (TrangThai <> 'USED' AND DaDungLuc IS NULL))
) ENGINE=InnoDB;

CREATE TABLE DatCho (
  DatChoID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  MaDatCho VARCHAR(24) NOT NULL,
  ClientRequestID CHAR(36) NOT NULL,
  XemTruocDatChoID BIGINT UNSIGNED NOT NULL,
  KhachHangID BIGINT UNSIGNED NOT NULL,
  CoSoLuuTruID BIGINT UNSIGNED NOT NULL,
  NgayNhanPhong DATE NOT NULL,
  NgayTraPhong DATE NOT NULL,
  TenNguoiDat VARCHAR(150) NOT NULL,
  EmailNguoiDat VARCHAR(190) NOT NULL,
  DienThoaiNguoiDat VARCHAR(20) NOT NULL,
  YeuCauDacBiet VARCHAR(1000) NULL,
  ThoiDiemThanhToan VARCHAR(24) NOT NULL,
  TienTe CHAR(3) NOT NULL DEFAULT 'VND',
  TongTien DECIMAL(14,2) NOT NULL,
  TrangThai VARCHAR(24) NOT NULL,
  HetHanThanhToanLuc DATETIME(6) NULL,
  XacNhanLuc DATETIME(6) NULL,
  HoanThanhLuc DATETIME(6) NULL,
  HuyIdempotencyKey CHAR(36) NULL,
  NguoiHuyID BIGINT UNSIGNED NULL,
  HuyLuc DATETIME(6) NULL,
  LyDoHuy VARCHAR(1000) NULL,
  PhiHuy DECIMAL(14,2) NOT NULL DEFAULT 0,
  SoTienHoan DECIMAL(14,2) NOT NULL DEFAULT 0,
  TinhHuySnapshotJSON JSON NULL,
  NguoiDanhDauNoShowID BIGINT UNSIGNED NULL,
  NoShowLuc DATETIME(6) NULL,
  PhiNoShow DECIMAL(14,2) NOT NULL DEFAULT 0,
  NoShowSnapshotJSON JSON NULL,
  TaoLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CapNhatLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY UQ_DatCho_Ma (MaDatCho),
  UNIQUE KEY UQ_DatCho_ClientRequest (ClientRequestID),
  UNIQUE KEY UQ_DatCho_Preview (XemTruocDatChoID),
  UNIQUE KEY UQ_DatCho_HuyIdempotency (HuyIdempotencyKey),
  KEY IX_DatCho_Khach (KhachHangID, TaoLuc),
  KEY IX_DatCho_CoSo (CoSoLuuTruID, TrangThai, NgayNhanPhong),
  CONSTRAINT FK_DatCho_Preview FOREIGN KEY (XemTruocDatChoID) REFERENCES XemTruocDatCho(XemTruocDatChoID),
  CONSTRAINT FK_DatCho_Khach FOREIGN KEY (KhachHangID) REFERENCES NguoiDung(NguoiDungID),
  CONSTRAINT FK_DatCho_CoSo FOREIGN KEY (CoSoLuuTruID) REFERENCES CoSoLuuTru(CoSoLuuTruID),
  CONSTRAINT FK_DatCho_NguoiHuy FOREIGN KEY (NguoiHuyID) REFERENCES NguoiDung(NguoiDungID),
  CONSTRAINT FK_DatCho_NguoiNoShow FOREIGN KEY (NguoiDanhDauNoShowID) REFERENCES NguoiDung(NguoiDungID),
  CONSTRAINT CK_DatCho_Ngay CHECK (NgayNhanPhong < NgayTraPhong),
  CONSTRAINT CK_DatCho_ThanhToan CHECK (ThoiDiemThanhToan IN ('PAY_AT_PROPERTY','PAY_ONLINE')),
  CONSTRAINT CK_DatCho_Tien CHECK (TienTe = 'VND' AND TongTien >= 0 AND PhiHuy >= 0 AND SoTienHoan >= 0 AND PhiNoShow >= 0),
  CONSTRAINT CK_DatCho_TrangThai CHECK (TrangThai IN ('PENDING_PAYMENT','CONFIRMED','PAYMENT_FAILED','CANCELLED','NO_SHOW','COMPLETED')),
  CONSTRAINT CK_DatCho_HuyMetadata CHECK (
    (TrangThai = 'CANCELLED' AND HuyIdempotencyKey IS NOT NULL AND NguoiHuyID IS NOT NULL AND HuyLuc IS NOT NULL AND LyDoHuy IS NOT NULL AND TinhHuySnapshotJSON IS NOT NULL) OR
    (TrangThai <> 'CANCELLED' AND HuyIdempotencyKey IS NULL AND NguoiHuyID IS NULL AND HuyLuc IS NULL AND LyDoHuy IS NULL AND PhiHuy = 0 AND SoTienHoan = 0 AND TinhHuySnapshotJSON IS NULL)
  ),
  CONSTRAINT CK_DatCho_NoShowMetadata CHECK (
    (TrangThai = 'NO_SHOW' AND NguoiDanhDauNoShowID IS NOT NULL AND NoShowLuc IS NOT NULL AND NoShowSnapshotJSON IS NOT NULL) OR
    (TrangThai <> 'NO_SHOW' AND NguoiDanhDauNoShowID IS NULL AND NoShowLuc IS NULL AND PhiNoShow = 0 AND NoShowSnapshotJSON IS NULL)
  )
) ENGINE=InnoDB;

CREATE TABLE HangMucDatCho (
  HangMucDatChoID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  DatChoID BIGINT UNSIGNED NOT NULL,
  SanPhamPhongID BIGINT UNSIGNED NOT NULL,
  LoaiPhongID BIGINT UNSIGNED NOT NULL,
  ThuTuPhong SMALLINT UNSIGNED NOT NULL,
  TenLoaiPhongSnapshot VARCHAR(150) NOT NULL,
  TenSanPhamSnapshot VARCHAR(150) NOT NULL,
  LoaiBuaAnSnapshot VARCHAR(24) NOT NULL,
  KhachJSON JSON NOT NULL,
  TongTien DECIMAL(14,2) NOT NULL,
  SnapshotDieuKienJSON JSON NOT NULL,
  SnapshotHuyJSON JSON NOT NULL,
  UNIQUE KEY UQ_HangMuc_ThuTu (DatChoID, ThuTuPhong),
  KEY IX_HangMuc_SanPham (SanPhamPhongID),
  CONSTRAINT FK_HangMuc_DatCho FOREIGN KEY (DatChoID) REFERENCES DatCho(DatChoID),
  CONSTRAINT FK_HangMuc_SanPham FOREIGN KEY (SanPhamPhongID) REFERENCES SanPhamPhong(SanPhamPhongID),
  CONSTRAINT FK_HangMuc_Phong FOREIGN KEY (LoaiPhongID) REFERENCES LoaiPhong(LoaiPhongID),
  CONSTRAINT CK_HangMuc_ThuTu CHECK (ThuTuPhong > 0),
  CONSTRAINT CK_HangMuc_Tien CHECK (TongTien >= 0)
) ENGINE=InnoDB;

CREATE TABLE GiaDemDatCho (
  HangMucDatChoID BIGINT UNSIGNED NOT NULL,
  NgayLuuTru DATE NOT NULL,
  GiaCoBan DECIMAL(14,2) NOT NULL,
  TienGiam DECIMAL(14,2) NOT NULL DEFAULT 0,
  ThuePhiDaGom DECIMAL(14,2) NOT NULL DEFAULT 0,
  ThuePhiTaiCoSo DECIMAL(14,2) NOT NULL DEFAULT 0,
  ThanhTien DECIMAL(14,2) NOT NULL,
  KhuyenMaiID BIGINT UNSIGNED NULL,
  SnapshotJSON JSON NOT NULL,
  PRIMARY KEY (HangMucDatChoID, NgayLuuTru),
  KEY IX_GiaDem_KhuyenMai (KhuyenMaiID),
  CONSTRAINT FK_GiaDem_HangMuc FOREIGN KEY (HangMucDatChoID) REFERENCES HangMucDatCho(HangMucDatChoID),
  CONSTRAINT FK_GiaDem_KhuyenMai FOREIGN KEY (KhuyenMaiID) REFERENCES KhuyenMai(KhuyenMaiID),
  CONSTRAINT CK_GiaDem_Tien CHECK (GiaCoBan > 0 AND TienGiam >= 0 AND ThuePhiDaGom >= 0 AND ThuePhiTaiCoSo >= 0 AND ThanhTien >= 0)
) ENGINE=InnoDB;

CREATE TABLE GiuTonPhongDem (
  GiuTonPhongDemID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  HangMucDatChoID BIGINT UNSIGNED NOT NULL,
  LoaiPhongID BIGINT UNSIGNED NOT NULL,
  NgayLuuTru DATE NOT NULL,
  TrangThai VARCHAR(12) NOT NULL,
  HetHanLuc DATETIME(6) NULL,
  GiuLuc DATETIME(6) NOT NULL,
  NhaLuc DATETIME(6) NULL,
  LyDoNha VARCHAR(32) NULL,
  UNIQUE KEY UQ_GiuTon_HangMucNgay (HangMucDatChoID, NgayLuuTru),
  KEY IX_GiuTon_DoiSoat (LoaiPhongID, NgayLuuTru, TrangThai),
  KEY IX_GiuTon_HetHan (TrangThai, HetHanLuc),
  CONSTRAINT FK_GiuTon_HangMuc FOREIGN KEY (HangMucDatChoID) REFERENCES HangMucDatCho(HangMucDatChoID),
  CONSTRAINT FK_GiuTon_Phong FOREIGN KEY (LoaiPhongID) REFERENCES LoaiPhong(LoaiPhongID),
  CONSTRAINT CK_GiuTon_TrangThai CHECK (TrangThai IN ('ACTIVE','RELEASED')),
  CONSTRAINT CK_GiuTon_Nha CHECK ((TrangThai = 'ACTIVE' AND NhaLuc IS NULL AND LyDoNha IS NULL) OR (TrangThai = 'RELEASED' AND NhaLuc IS NOT NULL AND LyDoNha IS NOT NULL))
) ENGINE=InnoDB;

CREATE TABLE ThanhToan (
  ThanhToanID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  DatChoID BIGINT UNSIGNED NOT NULL,
  ThoiDiemThanhToan VARCHAR(24) NOT NULL,
  TrangThai VARCHAR(16) NOT NULL,
  TongPhaiTra DECIMAL(14,2) NOT NULL,
  DaThanhToan DECIMAL(14,2) NOT NULL DEFAULT 0,
  DaHoan DECIMAL(14,2) NOT NULL DEFAULT 0,
  TienTe CHAR(3) NOT NULL DEFAULT 'VND',
  Provider VARCHAR(24) NULL,
  IdempotencyKey CHAR(36) NULL,
  ProviderReference VARCHAR(100) NULL,
  SoLanThu SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  MaLoiCuoi VARCHAR(80) NULL,
  XuLyLuc DATETIME(6) NULL,
  HoanTienIdempotencyKey CHAR(36) NULL,
  TrangThaiHoanTien VARCHAR(16) NOT NULL DEFAULT 'NONE',
  ProviderRefundReference VARCHAR(100) NULL,
  LyDoHoanTien VARCHAR(500) NULL,
  HoanTienHoanTatLuc DATETIME(6) NULL,
  TaoLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CapNhatLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY UQ_ThanhToan_DatCho (DatChoID),
  UNIQUE KEY UQ_ThanhToan_Idempotency (IdempotencyKey),
  UNIQUE KEY UQ_ThanhToan_HoanIdempotency (HoanTienIdempotencyKey),
  UNIQUE KEY UQ_ThanhToan_ProviderRef (Provider, ProviderReference),
  CONSTRAINT FK_ThanhToan_DatCho FOREIGN KEY (DatChoID) REFERENCES DatCho(DatChoID),
  CONSTRAINT CK_ThanhToan_Timing CHECK (ThoiDiemThanhToan IN ('PAY_AT_PROPERTY','PAY_ONLINE')),
  CONSTRAINT CK_ThanhToan_TrangThai CHECK (TrangThai IN ('NOT_TRACKED','PROCESSING','PAID','FAILED')),
  CONSTRAINT CK_ThanhToan_HoanTrangThai CHECK (TrangThaiHoanTien IN ('NONE','PENDING','SUCCEEDED','FAILED')),
  CONSTRAINT CK_ThanhToan_Tien CHECK (TienTe = 'VND' AND TongPhaiTra >= 0 AND DaThanhToan >= 0 AND DaHoan >= 0 AND DaHoan <= DaThanhToan),
  CONSTRAINT CK_ThanhToan_TaiCoSo CHECK (
    ThoiDiemThanhToan <> 'PAY_AT_PROPERTY' OR
    (TrangThai = 'NOT_TRACKED' AND DaThanhToan = 0 AND DaHoan = 0 AND Provider IS NULL AND IdempotencyKey IS NULL AND ProviderReference IS NULL AND SoLanThu = 0 AND MaLoiCuoi IS NULL AND XuLyLuc IS NULL AND HoanTienIdempotencyKey IS NULL AND TrangThaiHoanTien = 'NONE' AND ProviderRefundReference IS NULL AND LyDoHoanTien IS NULL AND HoanTienHoanTatLuc IS NULL)
  ),
  CONSTRAINT CK_ThanhToan_Online CHECK (
    ThoiDiemThanhToan <> 'PAY_ONLINE' OR
    (TrangThai IN ('PROCESSING','PAID','FAILED') AND Provider IS NOT NULL AND IdempotencyKey IS NOT NULL AND SoLanThu > 0)
  ),
  CONSTRAINT CK_ThanhToan_HoanMetadata CHECK (
    (TrangThaiHoanTien = 'NONE' AND DaHoan = 0 AND HoanTienIdempotencyKey IS NULL AND ProviderRefundReference IS NULL AND LyDoHoanTien IS NULL AND HoanTienHoanTatLuc IS NULL) OR
    (TrangThaiHoanTien IN ('PENDING','FAILED') AND HoanTienIdempotencyKey IS NOT NULL AND LyDoHoanTien IS NOT NULL AND HoanTienHoanTatLuc IS NULL) OR
    (TrangThaiHoanTien = 'SUCCEEDED' AND DaHoan > 0 AND HoanTienIdempotencyKey IS NOT NULL AND ProviderRefundReference IS NOT NULL AND LyDoHoanTien IS NOT NULL AND HoanTienHoanTatLuc IS NOT NULL)
  )
) ENGINE=InnoDB;

CREATE TABLE YeuCauHuyMienPhi (
  YeuCauHuyMienPhiID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  DatChoID BIGINT UNSIGNED NOT NULL,
  NguoiYeuCauID BIGINT UNSIGNED NOT NULL,
  LyDo VARCHAR(1000) NOT NULL,
  TrangThai VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  NguoiXuLyID BIGINT UNSIGNED NULL,
  PhanHoi VARCHAR(1000) NULL,
  TaoLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  XuLyLuc DATETIME(6) NULL,
  KEY IX_YeuCauHuy_Booking (DatChoID, TrangThai, TaoLuc),
  CONSTRAINT FK_YeuCauHuy_DatCho FOREIGN KEY (DatChoID) REFERENCES DatCho(DatChoID),
  CONSTRAINT FK_YeuCauHuy_NguoiYeuCau FOREIGN KEY (NguoiYeuCauID) REFERENCES NguoiDung(NguoiDungID),
  CONSTRAINT FK_YeuCauHuy_NguoiXuLy FOREIGN KEY (NguoiXuLyID) REFERENCES NguoiDung(NguoiDungID),
  CONSTRAINT CK_YeuCauHuy_TrangThai CHECK (TrangThai IN ('PENDING','APPROVED','REJECTED','WITHDRAWN')),
  CONSTRAINT CK_YeuCauHuy_XuLy CHECK ((TrangThai = 'PENDING' AND NguoiXuLyID IS NULL AND XuLyLuc IS NULL) OR (TrangThai = 'WITHDRAWN' AND NguoiXuLyID IS NULL) OR (TrangThai IN ('APPROVED','REJECTED') AND NguoiXuLyID IS NOT NULL AND XuLyLuc IS NOT NULL))
) ENGINE=InnoDB;

CREATE TABLE DanhGia (
  DanhGiaID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  DatChoID BIGINT UNSIGNED NOT NULL,
  CoSoLuuTruID BIGINT UNSIGNED NOT NULL,
  KhachHangID BIGINT UNSIGNED NOT NULL,
  DiemTong TINYINT UNSIGNED NOT NULL,
  DiemSachSe TINYINT UNSIGNED NULL,
  DiemViTri TINYINT UNSIGNED NULL,
  DiemNhanVien TINYINT UNSIGNED NULL,
  DiemThoaiMai TINYINT UNSIGNED NULL,
  DiemTienNghi TINYINT UNSIGNED NULL,
  DiemDangTien TINYINT UNSIGNED NULL,
  BinhLuan TEXT NULL,
  TrangThai VARCHAR(16) NOT NULL DEFAULT 'PUBLISHED',
  TaoLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY UQ_DanhGia_DatCho (DatChoID),
  KEY IX_DanhGia_CoSo (CoSoLuuTruID, TrangThai, TaoLuc),
  CONSTRAINT FK_DanhGia_DatCho FOREIGN KEY (DatChoID) REFERENCES DatCho(DatChoID),
  CONSTRAINT FK_DanhGia_CoSo FOREIGN KEY (CoSoLuuTruID) REFERENCES CoSoLuuTru(CoSoLuuTruID),
  CONSTRAINT FK_DanhGia_Khach FOREIGN KEY (KhachHangID) REFERENCES NguoiDung(NguoiDungID),
  CONSTRAINT CK_DanhGia_Diem CHECK (
    DiemTong BETWEEN 1 AND 10 AND
    (DiemSachSe IS NULL OR DiemSachSe BETWEEN 1 AND 10) AND
    (DiemViTri IS NULL OR DiemViTri BETWEEN 1 AND 10) AND
    (DiemNhanVien IS NULL OR DiemNhanVien BETWEEN 1 AND 10) AND
    (DiemThoaiMai IS NULL OR DiemThoaiMai BETWEEN 1 AND 10) AND
    (DiemTienNghi IS NULL OR DiemTienNghi BETWEEN 1 AND 10) AND
    (DiemDangTien IS NULL OR DiemDangTien BETWEEN 1 AND 10)
  ),
  CONSTRAINT CK_DanhGia_TrangThai CHECK (TrangThai IN ('PUBLISHED','HIDDEN'))
) ENGINE=InnoDB;

CREATE TABLE NhatKyHeThong (
  NhatKyHeThongID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NguoiThucHienID BIGINT UNSIGNED NULL,
  HanhDong VARCHAR(80) NOT NULL,
  LoaiDoiTu VARCHAR(80) NOT NULL,
  DoiTuID VARCHAR(80) NOT NULL,
  RequestID VARCHAR(80) NULL,
  DuLieuTruocJSON JSON NULL,
  DuLieuSauJSON JSON NULL,
  DiaChiIP VARCHAR(45) NULL,
  TaoLuc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY UQ_NhatKy_Request (RequestID),
  KEY IX_NhatKy_DoiTu (LoaiDoiTu, DoiTuID, TaoLuc),
  KEY IX_NhatKy_NguoiDung (NguoiThucHienID, TaoLuc),
  CONSTRAINT FK_NhatKy_NguoiDung FOREIGN KEY (NguoiThucHienID) REFERENCES NguoiDung(NguoiDungID)
) ENGINE=InnoDB;

SET FOREIGN_KEY_CHECKS = 1;
